export const i18nObj = {
  en: {
    socials: 'Social media',
    ['about-link']: 'About me',
    ['about-subtitle']: 'My name is Yana',
    ['experience-link']: 'My experience',
    ['skills-link']: 'My skills',
    ['jobs-link']: 'My works',
    ['price-link']: 'My price',
    ['contacts-link']: 'Contacts',
    ['strong-title']: 'I am Front-end developer',
    ['strong-label']: "Let's turn your idea into reality!",
    ['experience-education']: 'My experience and education',
    fullname: 'My name is Yana Pranko',
    title: `I am web developer from Minsk`,
    portfolio: 'Portfolio',
    parag1: `I create products for various purposes: portfolio website, online store, blog, page for demonstrating services, advertising pages, games,
              applications, quizzes and much more!`,
    parag2: `For me, this is not just a hobby, but a dream that has become a reality, so I take my work seriously, but at the same time with inspiration.`,
    parag3: `On my website you will find all the information you need and you can see examples of my work.`,
    parag4: `When implementing a project, I don't just transfer the design from the layout to the website, I care about reliability
              layout, the need and possibility of making changes to the original layout.`,
    parag5: `I create reliable, customized, beautiful websites, blogs, online stores and much more!`,
    parag6: `I create dynamic and engaging single page applications using React, Redux Toolkit.
              With a strong focus on optimization and performance, I strive to create smooth and responsive
              layouts that provide an exceptional user experience on all devices.`,
    parag7: `As part of the internship, I created a blog of articles using technologies such as: React, Typescript,
Redux Toolkit, RTK Query, Jest, React Testing Library, Storybook.`,
    parag8: `Code optimization technologies were used within the project; most of the code was covered with tests.
different formats. A component showcase has been created. During the work on the project we used
approaches: FSD architecture, CI/CD and much more`,
    parag9: `Blog features: authorization by roles, commenting on profiles, articles, editing a profile, searching, sorting articles, lazy loading of articles. The blog uses 3 color schemes, 2 languages.`,
    web: 'Web development',
    spa: 'Application Development',
    experience: 'Experience',
    education: 'Education',
    university: 'Belarusian state university',
    diploma: 'Diploma with honors | Minsk (2006-2011)',
    resume: `Graduate of the Faculty of History of the Belarusian State University. Specialty: 'Documentation and management information support',
            specialization: 'protection information'. Graduated with honors.`,
    js: `Successfully completed the JS/Frontend course, participated and defended a team project (game clone 'Colonist')`,
    react: `Successfully completed the React course, participated and defended a team project (query editor GraphiQL)`,
    trainee: 'Intership',
    startup: 'Startup',
    freelance: 'Freelance',
    upwork: 'Upwork (currently)',
    ready:
      'Currently I work as a freelancer, but at the same time I am open to offers!',
    working: 'I have completed and continue to perform various types of work.',
    skills: 'Skills',
    used: 'What do I use at work?',
    html: `It is he who creates the framework of your site or application, and the fifth version will allow me to create more SEO-optimized structure of your product`,
    css: `This styling language allows me to create absolutely any look and feel for your site or application. All limited only by your imagination!`,
    javascript: `This programming language allows you to bring anything to life: sliders, windows, tooltips, tabs, receiving data from the server and much more`,
    ts: 'This language allows you to prevent errors even at the coding stage!',
    ['react-skill']: `This library allows you to create web applications. We can create the most interactive product specifically for your purposes`,
    redux: `This state manager allows you to create scalable web applications. The main purpose is to make data management more organized and predictable.`,
    eslint: `A tool that allows you to keep your code 'clean' so that another developer can understand it later`,
    webpack: `A module builder that allows you to compile JavaScript modules into a single JS file. Also works with TypeScript`,
    storybook: `It is a tool for organizing user interfaces that makes development processes components, testing and documentation more efficient and simpler. With its help you can create a 'showcase' of components.`,
    jest: `A JavaScript/Typescript testing framework designed to provide confidence that any JavaScript/Typescript code will work correctly.`,
    sites: `Website development`,
    data: `Working with data`,
    creativity: `Creativity`,
    testing: 'Application testing',
    soft: 'Soft skills',
    from: 'from',
    landing: 'One-page website for the presentation of services/products/...',
    ['web-app']: 'Web application',
    app: 'Application inside the browser for better comfort',
    corporate: 'Corporate website',
    business: `Website for your business or company`,
    shop: 'Online store',
    sales: 'A tool for your online sales',
    contact: 'Contact me',
    way: 'In any way convenient for you:',
    myself: 'Or leave your details and I will write to you myself:',
    ['your-name']: 'Your name',
    email: 'Your email',
    message: 'Your message',
    submit: 'Send a message',
    agree: 'I agree with ',
    policy: 'privacy policy',
    ['Это обязательное поле']: 'This is a required field',
    ['Неверный email']: 'Invalid email',
  },
  ru: {
    socials: 'Социальные сети',
    ['about-link']: 'Обо мне',
    ['about-subtitle']: 'Меня зовут Яна',
    ['experience-link']: 'Мой опыт',
    ['skills-link']: 'Мои навыки',
    ['jobs-link']: 'Мои работы',
    ['price-link']: 'Прайс-лист',
    ['contacts-link']: 'Контакты',
    ['strong-title']: 'Я Front-end разработчик!',
    ['strong-label']: 'Давайте воплотим вашу	идею в реальность!',
    ['experience-education']: 'Мой опыт и образование',
    fullname: 'Меня зовут Яна Пронько',
    title: `Я web-разработчик из города Минск`,
    portfolio: 'Портфолио',
    parag1: `Создаю продукты для различных целей: сайт-портфолио, интернет-магазин, блог, страница для демонстрации услуг, рекламные страницы, игры,
						приложения, квизы и многое другое!`,
    parag2: `Для меня это не просто хобби, а мечта, которая стала реальностью, поэтому я отношусь к своей работе серьезно, но в тоже время с вдохновением.`,
    parag3:
      'На моем сайте вы найдете	всю нужную для вас информацию и можете посмотреть примеры моих работ.',
    parag4: `При реализации проекта, я не просто переношу дизайн с макета на вебсайт, я забочусь о надежности
							верстки, о необходимости и возможности внесения изменений в первоначальную верстку.`,
    parag5: `Создаю надежные, адаптированные, красивые вебсайты, блоги, интернет-магазины и многое другое!`,
    parag6: `Создаю динамичные и увлекательные одностраничные приложения с использованием React, Redux Toolkit.
										Уделяя особое внимание оптимизации и производительности, я стремлюсь создавать плавные и отзывчивые
										макеты,	обеспечивающие исключительный пользовательский опыт на всех устройствах.`,
    parag7: `В рамках стажировки создала блог статей, с использованием таких технологий как: React, Typescript,
											Redux Toolkit, RTK Query, Jest, React Testing Library, Storybook.`,
    parag8: `В рамках проекта использовались технологии оптимизации кода, большая часть кода покрыта тестами
											разного формата. Создана витрина компонентов. В процессе работы над проектом использовались
											подходы: FSD архитектура, CI/CD и многое другое.`,
    parag9: `Возможности блога: авторизация по ролям, комментирование профилей, статей, редактирование	профиля, поиск, сортировка, статей, "ленивая" подгрузка статей.	В блоге используются 3 цветовые схемы, 2 языка.`,
    web: 'Web-разработка',
    spa: 'Разработка приложений',
    experience: 'Опыт',
    education: 'Образование',
    university: 'Белорусский государственный университет',
    diploma: 'Диплом с отличием | Минск (2006-2011)',
    resume: `Выпускница исторического факультета Белорусского государственного универстита. Специальность:
											"Документоведение и информационное обеспечение управления", специализация: "защита
											информации". Окончила с отличием.`,
    js: `Успешно прошла обучение по курсу JS/Frontend, участвовала и защитила командный проект(клон игры "Colonist")`,
    react:
      'Успешно прошла обучение по курсу React, участвовала и защитила командный проект(редактор запросов	GraphiQL)',
    trainee: 'Стажировка',
    startup: 'Стартап',
    freelance: 'Фриланс',
    upwork: 'Upwork (по настоящее время)',
    ready:
      'В настоящее время работаю на фрилансе, но в тоже время готова к предложениям!',
    working: 'Выполнила и продолжаю выполнять разноплановые работы.',
    skills: 'Навыки',
    used: 'Что я использую в работе',
    html: `Именно он создает каркас вашего сайта или приложения, а пятая версия позволит мне создавать более
								SEO-оптимизированную структуру вашего продукта`,
    css: `Этот язык стилей позволяет мне создавать абсолютно любой внешний вид вашего сайта или приложения. Все ограничивается только вашей фантазией!`,
    javascript: `Этот язык программирования позволяет оживить все что угодно: слайдеры, окна, подсказки, вкладки,	получение	данных от сервера и многое другое`,
    ts: 'Этот язык позволяет предотвратить ошибки еще на этапе написания кода!',
    ['react-skill']: `Эта библиотека позволяет создавать web-приложения. Мы можем создать максимально интерактивный продукт именно под ваши цели`,
    redux: `Этот стейт-менеджер позволяет создавать масштабируемые web-приложения.Основное назначение заключается в
								том, чтобы сделать управление данными более организованным и предсказуемым.`,
    eslint: `Инструмент, который позволяет поддерживать "чистоту" кода, чтобы в нем впоследствии смог разобраться	другой разработчик`,
    webpack: `Cборщик модулей, который позволяет скомпилировать JavaScript-модули в единый JS-файл. Также работает с TypeScript`,
    storybook: `Это инструмент для организации пользовательских интерфейсов, который делает процессы разработки
								компонентов, тестирования и создания документации более эффективными и простыми. С его помощью можно
								создать "витрину" компонентов.`,
    jest: `Фреймворк для тестирования JavaScript/Typescript, разработанный для обеспечения уверенности в правильной работе любого JavaScript/Typescript кода.`,
    sites: `Создание сайтов`,
    data: `Работа с данными`,
    creativity: 'Креативность',
    testing: `Тестирование приложений`,
    soft: 'Soft навыки',
    from: 'от',
    landing: 'Одностраничный сайт для презентации услуг/товаров/...',
    ['web-app']: 'Web-приложение',
    app: 'Приложение внутри браузера для лучшего комфорта',
    corporate: 'Корпоративный сайт',
    business: 'Сайт для вашего бизнеса или компании',
    shop: 'Интернет-магазин',
    sales: 'Инструмент для ваших продаж в сети',
    contact: 'Свяжитесь со мной',
    way: 'Любым удобным для вас способом:',
    myself: 'Или оставьте ваши данные и я сама вам напишу:',
    ['your-name']: 'Ваше имя',
    email: 'Ваш email',
    message: 'Ваше сообщение',
    submit: 'Отправить сообщение',
    agree: 'Я согласен(а) с ',
    policy: 'политикой конфиденциальности',
    ['Это обязательное поле']: 'Это обязательное поле',
    ['Неверный email']: 'Неверный email',
  },
};